### ISSUE TITLE
Working with the latest bluetooth turbidimeter interface

### ISSUE THREAD

**Issue by eak24** [ethan92429/post_widget_bt#1]
Hi @iamchriskelley and @danelimjoco !
Dane is a new POST team member who will be working on implementing the bluetooth turbidimeter module of POST! Chris is a grad student at Johns Hopkins who has been designing and iterating the BT turbidimeter. 

From now on I think we're gonna try to use just GitHub issues for communications because of all the lovely features. 

Chris, would it be possible to see the latest format that the BT values come over the BT serial port? The latest I have is the following JSON:

{
    "dt": "hhT",
    "id": "01010101",
    "rt": 1,
    "ts": 1460412719,
    "rd": {
        "tur": {
            "u": "ntu",
            "t": [60, 60, 60, 60],
            "d": [1.40, 1.38, 1.37, 1.52],
            "e": []
        }
    },
    "ge": [],
    "al": {}
}

glossary:
"dt" = device type
"id" = device id
"rt" = t/f recording timestamps
"ts" = if "rt", this holds the unix timestamp
"rd" = data container, holding keys (parameter abbreviations) and values (datasets)
    "tur" = turbidity
        "u" = units
        "t" = offset time (sec) from "ts", or from "ts" plus previous reading
       "d" = data value of reading, listed sequentially and index-matched to offset time in "t"
       "e" = error code for a given reading
"ge" = global error code (for device as a whole, e.g.)
"al" = alarm instructions (if device logic includes broadcasting alarms)

Is that still the JSON you are using? And where do you store the latest firmware so we can always stay up to date with your latest updates?

**Comment by iamchriskelley** [comment]
Hey @ethan92429 and @danelimjoco! 
Glad you're working on the BT functionality, Dane. The JSON spec listed above is still the most current -- for lab testing we just use plain text over serial so I haven't needed to update it. Do note that the handheld turbidimeter doesn't have an external RTC by default yet (it will after we switch over from the current RTC chip that costs $7/ea to a new one that costs <$1/ea), so you wouldn't normally be getting timestamped sets of readings. In this case, a normal reading would look more like:

{
"dt": "hhT",
"id": "01010101",
"rt": 0,
"ts": 0,
"rd": {
"tur": {
"u": "ntu",
"t": [0],
"d": [1.40],
"e": []
}
},
"ge": [],
"al": {}
}

Looks like we've been working locally on the lab computer; I'll push hardware, software, and caseware updates tomorrow to https://github.com/AWQUA/improved-handheld-turbidimeter.

**Comment by iamchriskelley** [comment]
Forgot to do the updates yesterday before I left the lab. They're up now. The firmware is just what was used for prototyping; I'll get JSON output included shortly.

**Comment by danelimjoco** [comment]
@iamchriskelley 
Hi Chris! Thank you for the JSON output. I'm starting to create dummy JSON objects in my java app now that look like the output from the turbidimeter and will try to handle the object accordingly. Keep me posted!

**Comment by danelimjoco** [comment]
@ethan92429 

Can you help me understand the two methods you wrote that parse the JSON String? I feel like I can leave the parseWithRegex method alone. I just don't understand the notation you use for the String pattern and why you pass the first_match into the parseWithRegex method again. Also are you trying to locate the value based on the location of "NTU"? Because in my output NTU doesn't appear adjacent to the value.

`public static float parseNtu(String string) {`
`String first_match = parseWithRegex(string, "(\\d+)(.)(\\d+)(\\s*)(NTU)");`
`String second_match = parseWithRegex(first_match, "(\\d+)(.)(\\d+)");`
`return Float.parseFloat(second_match);`
    `}`

`public static String parseWithRegex(String string, String pattern) {`
`// Create a Pattern object`
`Pattern r = Pattern.compile(pattern);`
`// Now create matcher object.`
`Matcher m = r.matcher(string);`
`if (m.find()) {`
`return m.group(0);`
`} else return "";`
`}`

I want to manipulate your methods so that I can extract the value "1.4" after the " "d":[ "

I converted the JSON object into a String that looks like this:
{"id":"01010101","dt":"hhT","al":"{}","ge":[],"rt":0,"ts":0,"rd":{"tur":{"d":[1.4],"u":"ntu","e":[],"t":[0]}}}

I tried modifying the parseNtu method to make it like this, but I think I'm returning null:

`public static float parseNtu(String string) {`
`String first_match = parseWithRegex(string, "{\"d\":[\\d+");`
`String second_match = parseWithRegex(first_match, "(\\d+)(.)(\\d+)");`
`return Float.parseFloat(second_match);`
`}`

By using the following method, I was able to extract 1010101.0 and populate the field!
`public static float parseNtu(String string) {`
`String second_match = parseWithRegex(string, "(\\d+)(.)(\\d+)");`
`return Float.parseFloat(second_match);`
`}`

Thank you in advance!

**Comment by eak24** [comment]
@danelimjoco I believe all of the parsing will have to be changed. In prior iterations of Chris's code, he didn't use JSON syntax. Now that he does, it makes our job much simpler because we don't need to implement any special parsing rules like I did before. Instead, we can turn the string that comes from the BT turbidimeter directly into a JSON object (because the BT code technically outputs a String type I believe) with the parser explained [here](http://stackoverflow.com/questions/18192891/conversion-from-string-to-json-object-android). After that, you can easily access all the appropriate fields very cleanly with the getDouble("tur") method. Does that help?

**Comment by eak24** [comment]
We will be using the java JSON parser.
