### ISSUE TITLE
Getting the latest BT turbidimeter

### ISSUE THREAD

**Issue by eak24** [ethan92429/post_widget_bt#2]
@iamchriskelley @danelimjoco 
I'm sorry Dane! I forgot I had sent back the turbidimeter to Chris because I thought it was broken! We currently do not have a BT turbidimeter in the lab. Chris, would it be possible to get one of the turbidimeters? In the meantime Dane can use the JSON interface we design in the other issue.

**Comment by iamchriskelley** [comment]
Can do. I can't get an appointment on the laser cutter (for the turbidimeter case) until Friday or Monday though, so I'll do my best to have this out before the 30th.

**Comment by eak24** [comment]
@iamchriskelley How did it go? Any luck fabricating the newest model? Thanks so much!

**Comment by iamchriskelley** [comment]
Hey folks,

The boards for the latest turbidimeter are in. I am getting married this
Sunday and am already in San Antonio getting everything ready. After the
wedding this Sunday and a "mini-moon" I'll be back in the lab for the last
week of the month. Will send assembly photos, test data, and a prototype
then.

Cheers,
Chris

On Oct 10, 2016 4:01 PM, "Ethan" notifications@github.com wrote:

@iamchriskelley https://github.com/iamchriskelley How did it go? Any luck
fabricating the newest model? Thanks so much!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/AguaClara/post.bluetooth/issues/2#issuecomment-252745122,
or mute the thread

**Comment by eak24** [comment]
@iamchriskelley 🍾 Congratulations! Enjoy your wedding! 😄

**Comment by iamchriskelley** [comment]
Thanks!

**Comment by danelimjoco** [comment]
Hi @iamchriskelley!

Hope your wedding and "mini-moon" went well!! Any updates on the turbidimeter? Let me know!

**Comment by iamchriskelley** [comment]
Hey @danelimjoco!

The wedding and time after were great, thanks. I got back to Baltimore last week and brought a cold with me that has proved remarkably tenacious. On antibiotics now and feeling better by the day. 

Will be in to the office tomorrow to move local copies of the turbidimeter's circuit boards to the repo. We parted things out, so there are several boards. After that I'll post performance data for the new analog front end, hopefully tomorrow afternoon.

**Comment by eak24** [comment]
Hi @iamchriskelley thanks for the update. We would like a turbidimeter to exp with ASAP (doesn't need to be the latest/greatest) so that @danelimjoco can finish up the BT code. I've recommended he use a BT terminal application to simulate a BT connection from the turbidimeter with another phone. Does that work well to simulate?

**Comment by iamchriskelley** [comment]
Hey @ethan92429 -- using one phone to send dummy data to another should work fine, but skip that mess and I'll mail you an older turbidimeter tomorrow morning.

**Comment by eak24** [comment]
We have a dummy turbidimeter in the lab thanks to Chris!
