### ISSUE TITLE
How does this app speed up process?

### ISSUE THREAD

**Issue by danelimjoco** [ethan92429/post_widget_bt#4]
Hey @ethan92429! 

Today I was finally able to populate the raw water turbidity field with the correct value from my dummy JSONObject output, so now all I need is an actual turbidimeter to test it. 

Since we have a presentation coming up soon, I wanted to ask you about the scope of the project, specifically, how this raw water turbidity button speeds up the process. Could you give me some details about how the BT Turbidimeter works, why raw water turbidity is important, how raw water turbidity is collected currently, and how much this external app speeds things up? It'd be great to have a better understanding of the context of this project. Thanks!

**Comment by eak24** [comment]
Hi @danelimjoco I'd love to!

The BT turbidimeter works the same way as any other turbidimeter. It shines light through a sample and measures how much is scattered to the side. The more scattered, the dirtier the water is.

This isn't just for raw water turbidity... it's for collecting all turbidities. Raw, settled and filtered. It's important and necessary to measure how well are plants are doing to make sure they are meeting national health standards (and hopefully surpassing!) Also because we want to make sure we're not making people sick. 

Turbidities are currently collected through a regular turbidimeter... the ops read the meter and copy down the value. A BT meter would make sure there's no error in copying down that number (we've had a number of typos with where the decimal is in the past) AND makes it easier for the op. Also, with BT, we're one step closer to having an autonomous plant monitoring system... a dream for larger plants that brings us closer to offering something better in all regards than the current state of the art mechanized plants. 

Not sure how much exactly this speeds things up... too early to say. 

Thanks for asking!! 😄

**Comment by danelimjoco** [comment]
Hi @ethan92429!

Right now I'm working on getting my java app ready for when the actual turbidimeter gets here. I don't understand what most of your code does for the methods findBT(), openBT(), and beginListenForData(), but I figure that the string which needs to be converted to a JSONObject is the "allOutput" string. 

Once the "allOutput" string is defined in the beginListenForData() method, I simply write `getDoubleFromString(allOutput)` which calls the following method I wrote:

```
 public void getDoubleFromString(String output){
        try{
            JSONObject obj = new JSONObject(output);
            Double mAnswer = obj.getJSONObject("rd").getJSONObject("tur").getJSONArray("d").getDouble(0);
            incomingIntent.putExtra("value", mAnswer);
            setResult(RESULT_OK, incomingIntent);
            finish();
        }
        catch(org.json.JSONException e) {
            System.out.println(e);
            finish();
        }
    }
```

This should work, assuming the string "allOutput" looks exactly like the dummy JSONObject I've been practicing with, but as a string. Are there any modifications you think I will need to make to findBT() or openBT() or beginListenForData()? Lastly, I call findBT() and openBT() right at the beginning of my code, so that the user doesn't have to press any buttons (it'll just run automatically in the background). Let me know what you think!

P.S. If there's anything else you can think of that I should work on in the meantime, let me know. I'm pretty much at a standstill until the Turbidimeter gets here.

**Comment by eak24** [comment]
Hi @danelimjoco, Thanks for reaching out. Whenever you feel stuck, you can always browse through the repos, look at the issues, and write a comment to me about it in the issue, and I can get you started. Those other methods are for setting up the connection with the bluetooth. You should be able to use them to connect to any bluetooth device. See what happens when you do. your app should be able to handle being connected to the wrong bluetooth device gracefully. Also, what does the UI look like? you need that for actually connecting! Last I remember it is atrocious! you can work on fixing that up. For now I think you have enough work with those tasks. 😄

**Comment by danelimjoco** [comment]
@ethan92429 

The UI is just three buttons: open, close, and send. It seems to me that by pressing the "open" button, and then the send button, things will be taken care of. But I thought the UI shouldn't matter for the java app since it should run in the background? Therefore I was thinking of just calling the methods triggered by the open and send buttons right from the beginning. Then I can call the method I wrote which will close the app and send the value. Does this sound right?

**Comment by eak24** [comment]
Try connecting it to some other BT enabled object. You can broadcast a BT raw string from another phone using a BT terminal app...: https://play.google.com/store/apps/details?id=Qwerty.BluetoothTerminal&hl=en And I think you can get a similar type of app on your comp as well.

**Comment by eak24** [comment]
We have the dummy BT turbidimeter.
